### ISSUE TITLE
[Bug]: Error when launching container with any component packages other than base and signal-processing

### ISSUE THREAD

**Issue by rraetz** [aica-technology/api#137]
### Image manifest

```Shell
#syntax=ghcr.io/aica-technology/app-builder:v1

[packages]
"@aica/base" = "v3.1.1"

# add components
"@aica/components/signal-processing" = "v1.0.1"
# "@aica/components/auto-frame-calibration" = "v1.0.0"
# "@aica/components/dmp" = "v1.0.0"
"@aica/components/learning-components" = "v0.1.0"
# "@aica/components/pose-detection" = "v1.0.2"
# "@aica/components/task-optimization" = "v3.0.0"

# add hardware collections 
"@aica/collections/ur-collection" = "v3.0.4"
"@aica/collections/kinova-gen3-collection" = "v0.1.1"
```

### Brief description

The build of the manifest file works fine, but when I run the container, I get an error (see log output below).

When I build and run with only the base package, signal-processing and robot collections, I see that ROS2 version Iron is used. However, the error message above suggests that Humble is assumed. 

### Steps to reproduce

Just build and run with the provided toml file.

### Relevant log output

```Shell
[2024-03-13 09:40:31] INFO: starting daemon "nginx" as user "nginx"
not found: "/opt/ros/humble/local_setup.bash"
[2024-03-13 09:40:31] INFO: starting service "backend_api" as user "ros2"
[2024-03-13 09:40:31] INFO: starting service "py_component_manager" as user "ros2"
Traceback (most recent call last):
  File "/services/start.py", line 270, in <module>
    sys.exit(main())
  File "/services/start.py", line 264, in main
    supe.start(services=SERVICES)
  File "/services/start.py", line 142, in start
    pid = self.start_process(
  File "/services/start.py", line 79, in start_process
    res = subprocess.Popen(
  File "/usr/lib/python3.10/subprocess.py", line 971, in __init__
    self._execute_child(args, executable, preexec_fn, close_fds,
  File "/usr/lib/python3.10/subprocess.py", line 1863, in _execute_child
    raise child_exception_type(errno_num, err_msg, err_filename)
FileNotFoundError: [Errno 2] No such file or directory: 'ros2'
```

**Comment by domire8** [comment]
Thanks for this bug report! As discussed in person, the DMP and learning components packages are indeed so old that they were built on ROS humble. I will start a discussion internally to see how we can handle this. For the moment, you don't need these component packages anyway.

**Comment by eeberhard** [comment]
As @domire8 said, some packages are now out of date with respect to the newest framework and base image version. We will gradually be updating packages to ensure compatibility with the newest versions, and moreover are working on capturing inter-package dependencies (such as the ROS base version they expect) more explicitly to prevent this issue from arising in future. As this is a general ongoing infrastructural endeavor, I will close this issue for the time being. In the meantime, thank you for your feedback and patience with our beta program!
