### ISSUE TITLE
[Bug]: License not assigned to email yields error in registry

### ISSUE THREAD

**Issue by rrosa24** [aica-technology/api#149]
### Image manifest

```Shell
Error response from daemon: Get "https://registry.licensing.aica.tech/v2/": unauthorized: {"errors":[{"code":"UNAUTHORIZED","message":"authentication required (FAILED): license has no user, storage is unavailable"}]}
```

### Brief description

Unable to login to registry with beta license, was fixed by adding an email to license in license key admin

### Steps to reproduce

Login to registry with a license not tied to email on license portal yields error

**Comment by LouisBrunner** [comment]
As discussed offline, we expect all customers to have an email associated with their account in our licensing management.
