### ISSUE TITLE
Support `rate` parameter for components in YAML syntax

### ISSUE THREAD

**Issue by domire8** [aica-technology/api#47]
>Yes, it's a fair point. The name `period` was held over from the modulo `Cell` days because it was the input to the wall timer function (a period for the timer to wait). Conversely the `rate` term was adopted from the ros2_control stack, where control engineers like to think about frequencies. 

>I don't know which one of period or frequency/rate is more intuitive, but mixing the two in one syntax is not ideal. A `period` for periodic behavior is quite nice conceptually, but I would also not be against components having a rate instead. Only problem is that it would be a breaking change unless we support both parameters, and in that case we would need to decide which one to prioritize if both are set.

_Originally posted by @eeberhard in https://github.com/aica-technology/api/pull/45#discussion_r1324522631_

**Comment by eeberhard** [comment]
You really went all in on the issue name 😅

**Comment by domire8** [comment]
I accidentally clicked enter too early :eyes:

**Comment by eeberhard** [comment]
The implementation of the issue is covered by https://github.com/aica-technology/modulo/issues/52. This issue might still be good to re-open later since it will involve changes to the application schema.

**Comment by domire8** [comment]
This required changes after modulo#52 were made in https://github.com/aica-technology/api/pull/63
