### ISSUE TITLE
Move switch controller to different endpoint

### ISSUE THREAD

**Issue by domire8** [aica-technology/api#53]
I've realized that the switch controller endpoint is under `v1/application/hardware`, so each time you call it, you also have to provide the interface name as part of the request. Why don't we put it under `v1/application/hardware/{interface_name}`?

@eeberhard @jjenscodee

**Comment by eeberhard** [comment]
Minor correction, it's currently a PUT request under `v1/application/controllers` and takes the payload `{interface, start, stop}`.

One problem is that `v1/application/hardware/{interface_name}` already has PUT and DELETE for load/unload hardware respectively, so the same endpoint for switching controllers would not work. Secondly, it would not be RESTful to manage controllers under a hardware endpoint.

Still, based on your idea, I would be happy with the following:

`v1/application/controllers` 
-- change to -->
`v1/application/hardware/{interface_name}/controllers`

**Comment by domire8** [comment]
Yes, indeed. I somehow already implemented it that way but it's true that I missed that detail in the issue description.

**Comment by eeberhard** [comment]
Actually, I forgot to bring it up beforehand, but is this maybe a good time to also change `start` and `stop` to `activate` and `deactivate` respectively? That would also be a YAML syntax change. It's another small thing that would be breaking but could be nice to do it now

**Comment by domire8** [comment]
Should we do a separate issue for this? It will come with PRs in DSE and backend-api and I find it easier to scope if we separate

**Comment by eeberhard** [comment]
Yes please, add it to [#110](https://github.com/aica-technology/backend-api/issues/110)
