### ISSUE TITLE
Document the API endpoints automatically

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#7]
Swagger

**Comment by eeberhard** [comment]
It's a really good start! I'm pleased to see on the feature branch how nicely it works without huge changes. Now that we know a bit better what we are dealing with, I would prefer to break these into separate implementation PRs

For this issue:
- Switching from `flask_restful` to `flask-restx` and making sure nothing else breaks (e.g. maintaining the Resource and API factory patterns).
- Adding documentation and decorator routes for swagger

For a secondary issue / milestone:
- Renaming routes and namespaces (as this requires some design discussions, and changes must be propagated to the API clients in python and frontend)

**Comment by domire8** [comment]
Okay that's reasonable. Do you want me to investigate more on the response decorators? I couldn't quite figure out yet which response codes I need to document and what we actually respond.

Also,
1. Why do we need the default resource?
2. The response model of the `/component_descriptions` could technically be added as well and we could probably even import the schema but that seems a bit overkill. What do you think?

**Comment by eeberhard** [comment]
> Why do we need the default resource?

We don't need it. Currently it's just a basic GET to check the API is working. I was also intending to put something more descriptive like "AICA API version 0.2". But in the case of swagger, the default route can return the HTML docs which is even better.

**Comment by eeberhard** [comment]
For point 2 I think it can wait, but I agree we could link to or use the schema in interesting ways

**Comment by domire8** [comment]
> But in the case of swagger, the default route can return the HTML docs which is even better.

So we would load a `.html` file as string and return its content? This would mean that the html file would become part of the package, kind of like the descriptions, is this what you'd envision?

**Comment by domire8** [comment]
Ah okay, I guess I'm still a bit confused by the terminology and how the whole API thing works. And then by the fact that even though the default endpoint is now the swagger documentation (as I understand from your explanation), it is still listed as one of the endpoints.

**Comment by domire8** [comment]
Maybe this could be an option too:
https://readthedocs.com/?utm_source=readthedocs&utm_campaign=aug-3-deployment-get-started&ea-publisher=readthedocs

**Comment by domire8** [comment]
As per our discussion during the sprint planning:

1. The concrete steps for the API are:
    - Refine swagger documentation with more decorators and cleaner names/descriptions
    - Publish that html on a public page in the api repo
2. A 'readthedocs' with manually written READMEs for 'getting started' and similar could come in a future epic (after 7.0 release) and is complementary to developer pages generated by doxygen.
