### ISSUE TITLE
Desired usage of schemas

### ISSUE THREAD

**Issue by domire8** [aica-technology/api#79]
@LouisBrunner @eeberhard @jjenscodee 

PR #78 fixed some issues with the schemas. However, we are still not sure where we are going with the schemas and what the desired usage is at the end. I will try to summarize what we have right now:

### What's possible

We can tell vscode to look up the schema from our docs page in a `settings.json` and we get autocomplete and validation.

### What's not possible

Putting a `"$schema"` tag at the beginning of the file doesn't work in vscode because it cannot resolve nested references in the schema.

### What's possible

We can use the YAML extension in vscode and configure the `settings.json` to look up the yaml syntax from the docs page.

### What's not possible

What do we want?

---

As far as I understand, it would be desirable to have the schema link be put directly inside the files that we are trying to validate because only like that can we 'control' what version is should be validated against. 
- For the component/controller descriptions, I think the problem with the nested reference is a problem that one can fix
- For the application, I'm really not sure how we should achieve that. Do you guys have an idea of what the goal would be for the YAML files?

**Comment by jjenscodee** [comment]
From @eeberhard:
> At this point, the backend API now already does the job of “expanding” component descriptions by looking up the inheritance chain and building a new flat description for each component. We never actually use the nested reference for inheritance. Therefore, my suggestion would be to deprecate the nested inheritance property and just use this:
> ```
> "inherits": {
>   "$ref": "#/$defs/registration"
> }
> ```

**Comment by eeberhard** [comment]
TODO: make a new epic containing these points:

https://github.com/aica-technology/api/issues/62#issuecomment-1775575486

**Comment by domire8** [comment]
See #87
