### ISSUE TITLE
Setup a default GitHub page template and workflow

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#8]
Use a template to make a GitHub page that formats and serve a single markdown file (e.g. the top-level README)

**Comment by domire8** [comment]
As discussed, it might be nice to have all our documentation pages (e.g. html files) centralized in the `aica-technology.github.io` repository and create the `index.html` there. For that,

- [ ] Create a workflow on backend-api that exports the swagger documentation to html and puts it in a dedicated directory in the github.io repo
- [ ] Find a way to export markdown files (for example for the api repo) and push them to the github.io repo

**Comment by domire8** [comment]
https://domire8.github.io/.github/

**Comment by domire8** [comment]
As described in #7, the two steps necessary to complete this issue are (both in backend-api):

- [ ] Refine swagger documentation with more decorators and precise names/descriptions
- [ ] Push the generated html to the API repo and publish it as a github page
