### ISSUE TITLE
Include `get_application_state` endpoint in Python client

### ISSUE THREAD

**Issue by eeberhard** [aica-technology/api#9]

**Comment by domire8** [comment]
This is actually not so straight forward, because the API is still targeting the v0 endpoints. We have to start versioning this repo as well can keep the endpoints in sync

**Comment by eeberhard** [comment]
Agreed, the python client needs a bit of love to version and validate correctly, which should be a separate epic. I would suggest to wait for feedback from Louis for the best way to manage that though, since the python client isn't currently heavily used yet. You can either put the issue on hold, or implement it with the new endpoint just to validate that it works.

**Comment by eeberhard** [comment]
@jjenscodee this could be something for you. Now that the main refactors to the api server and client are complete, this could be achieved quite easily. The goal would be to return the result of the API call to GET `/v1/application/state` to see if the application is "unset", "set", "running" or "paused".

(pseudo-code)

```python3
def get_application_state(self):
    return get("/v1/application/state")
```
